"""Build (or check) the committed 9x9 medium puzzle pool for Cloudflare.

Generates exactly ``COUNT`` unique 9x9 puzzles with exactly ``GIVENS`` nonzero
clues each, using the existing ``game.sudoku`` engine and a single seeded
``random.Random`` instance so the pool is fully reproducible.  Every accepted
puzzle is independently re-validated with the naive backtracking oracle in
``game.tests.reference`` (a structurally different solver from the DLX engine
used to generate the puzzle) before it is written out.

Usage::

    python tools/codex-mhj_26_08_02_02_build_puzzle_pool.py --write
    python tools/codex-mhj_26_08_02_02_build_puzzle_pool.py --check

``--write`` regenerates and atomically replaces the runtime module and the
manifest.  ``--check`` regenerates the expected bytes in memory and compares
them against the committed files without writing anything; it exits nonzero
on any mismatch.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import random
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

from game.sudoku.generator import generate_puzzle  # noqa: E402
from game.sudoku.spec import spec_for  # noqa: E402
from game.tests.reference import count_solutions, is_valid_solution  # noqa: E402

SEED = 20260802
DIM = 9
DIFFICULTY = "medium"
GIVENS = 32
COUNT = 512
MAX_ATTEMPTS = 4096

SCHEMA_VERSION = 1

MODULE_PATH = REPO_ROOT / "cloudflare" / "codex-mhj_26_08_02_03_puzzle_pool.mjs"
MANIFEST_PATH = REPO_ROOT / "cloudflare" / "codex-mhj_26_08_02_04_puzzle_pool_manifest.json"
SUDOKU_SRC_DIR = REPO_ROOT / "game" / "sudoku"


class PoolBuildError(Exception):
    """Raised when the pool cannot be built or validated."""


def _build_entries() -> list[tuple[list[int], list[int]]]:
    """Generate exactly COUNT unique, independently-verified puzzles."""
    spec = spec_for(DIM)
    rng = random.Random(SEED)
    seen: set[tuple[int, ...]] = set()
    entries: list[tuple[list[int], list[int]]] = []

    attempts = 0
    while len(entries) < COUNT:
        if attempts >= MAX_ATTEMPTS:
            raise PoolBuildError(
                f"reached max attempts ({MAX_ATTEMPTS}) with only "
                f"{len(entries)}/{COUNT} accepted puzzles"
            )
        attempts += 1

        puzzle, solution = generate_puzzle(
            target_givens=GIVENS, dim=DIM, rng=rng, time_limit=float("inf"),
        )

        given_count = sum(1 for cell in puzzle if cell)
        if given_count != GIVENS:
            continue

        key = tuple(puzzle)
        if key in seen:
            continue

        if len(puzzle) != spec.cells or len(solution) != spec.cells:
            continue
        if any(not (0 <= v <= DIM) for v in puzzle):
            continue
        if any(not (1 <= v <= DIM) for v in solution):
            continue
        if any(pv != 0 and pv != sv for pv, sv in zip(puzzle, solution)):
            continue
        if not is_valid_solution(solution, spec):
            continue
        if count_solutions(puzzle, spec, limit=2) != 1:
            continue

        seen.add(key)
        entries.append((puzzle, solution))

    if len(entries) != COUNT:  # pragma: no cover - defensive, loop guarantees this
        raise PoolBuildError(f"expected {COUNT} entries, built {len(entries)}")

    return entries


def _canonical_entries_json(entries: list[tuple[list[int], list[int]]]) -> str:
    """Compact canonical JSON of [[puzzle, solution], ...], no whitespace."""
    payload = [[list(puzzle), list(solution)] for puzzle, solution in entries]
    return json.dumps(payload, separators=(",", ":"), sort_keys=False)


def _entries_sha256(entries_json: str) -> str:
    return hashlib.sha256(entries_json.encode("utf-8")).hexdigest()


def _source_sha256() -> str:
    """SHA-256 over sorted game/sudoku/*.py path + content."""
    digest = hashlib.sha256()
    for path in sorted(SUDOKU_SRC_DIR.glob("*.py")):
        rel = path.relative_to(REPO_ROOT).as_posix()
        digest.update(rel.encode("utf-8"))
        digest.update(b"\0")
        digest.update(path.read_bytes())
        digest.update(b"\0")
    return digest.hexdigest()


def _module_source(entries_json: str) -> str:
    return (
        "// Generated by tools/codex-mhj_26_08_02_02_build_puzzle_pool.py\n"
        "// Do not edit by hand; regenerate with --write.\n"
        "export const POOL_SCHEMA_VERSION = 1;\n"
        f"export const PUZZLE_POOL = {entries_json};\n"
    )


def _manifest_source(entries_sha256: str, source_sha256: str) -> str:
    manifest = {
        "schemaVersion": SCHEMA_VERSION,
        "count": COUNT,
        "dimension": DIM,
        "difficulty": DIFFICULTY,
        "givens": GIVENS,
        "seed": SEED,
        "entriesSha256": entries_sha256,
        "sourceSha256": source_sha256,
    }
    return json.dumps(manifest, separators=(",", ":"), sort_keys=False) + "\n"


def _expected_outputs() -> tuple[str, str]:
    entries = _build_entries()
    entries_json = _canonical_entries_json(entries)
    entries_sha256 = _entries_sha256(entries_json)
    source_sha256 = _source_sha256()
    module_text = _module_source(entries_json)
    manifest_text = _manifest_source(entries_sha256, source_sha256)
    return module_text, manifest_text


def _stage_temp(final_path: Path, text: str) -> Path:
    final_path.parent.mkdir(parents=True, exist_ok=True)
    tmp_path = final_path.parent / (
        f"codex-mhj_26_08_02_{os.getpid()}_tmp_{final_path.name}"
    )
    data = text.encode("utf-8")
    try:
        with open(tmp_path, "wb") as fh:
            fh.write(data)
            fh.flush()
            os.fsync(fh.fileno())
        written = tmp_path.read_bytes()
        if written != data:
            raise PoolBuildError(f"temp file verification failed for {final_path}")
        return tmp_path
    except BaseException:
        if tmp_path.exists():
            tmp_path.unlink()
        raise


def cmd_write() -> int:
    module_text, manifest_text = _expected_outputs()
    module_tmp = _stage_temp(MODULE_PATH, module_text)
    try:
        manifest_tmp = _stage_temp(MANIFEST_PATH, manifest_text)
    except BaseException:
        module_tmp.unlink(missing_ok=True)
        raise
    try:
        os.replace(module_tmp, MODULE_PATH)
        os.replace(manifest_tmp, MANIFEST_PATH)
    finally:
        module_tmp.unlink(missing_ok=True)
        manifest_tmp.unlink(missing_ok=True)
    print(f"wrote {MODULE_PATH.relative_to(REPO_ROOT)}")
    print(f"wrote {MANIFEST_PATH.relative_to(REPO_ROOT)}")
    return 0


def cmd_check() -> int:
    if not MODULE_PATH.exists():
        print(f"missing {MODULE_PATH.relative_to(REPO_ROOT)}", file=sys.stderr)
        return 1
    if not MANIFEST_PATH.exists():
        print(f"missing {MANIFEST_PATH.relative_to(REPO_ROOT)}", file=sys.stderr)
        return 1

    expected_module, expected_manifest = _expected_outputs()
    actual_module = MODULE_PATH.read_text(encoding="utf-8")
    actual_manifest = MANIFEST_PATH.read_text(encoding="utf-8")

    ok = True
    if actual_module != expected_module:
        print(f"MISMATCH: {MODULE_PATH.relative_to(REPO_ROOT)}", file=sys.stderr)
        ok = False
    if actual_manifest != expected_manifest:
        print(f"MISMATCH: {MANIFEST_PATH.relative_to(REPO_ROOT)}", file=sys.stderr)
        ok = False

    if not ok:
        return 1

    print("OK: committed puzzle pool matches regenerated expected output")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--write", action="store_true",
                       help="regenerate and atomically replace the pool module and manifest")
    group.add_argument("--check", action="store_true",
                       help="verify committed files match regenerated expected output; no writes")
    args = parser.parse_args(argv)

    try:
        if args.write:
            return cmd_write()
        return cmd_check()
    except (PoolBuildError, OSError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
